import { DOMAIN_RULES, MATERIAL_RULES, MICRO_TAG_RULES, PRIMARY_THEME_RULES, STRUCTURE_RULES } from './rules.js';
import { extractComments, normalizeText, parseHeaders, splitGames, stripHeadersAndComments } from './parser.js';
import type { PgnHeaders, TaxonomyRow, TaxonomyRule } from './types.js';
export function scoreRules(text:string,rules:TaxonomyRule[]):Map<string,number>{const n=normalizeText(text);const c=new Map<string,number>();for(const r of rules){let hits=0;for(const k of r.keywords)if(n.includes(normalizeText(k)))hits++;if(hits)c.set(r.label,(c.get(r.label)||0)+hits*r.weight)}return c}
export function topLabels(counter:Map<string,number>,limit:number,minScore:number,relativeCutoff:number):string[]{const entries=[...counter.entries()].filter(([,v])=>v>=minScore).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));if(!entries.length)return[];const top=entries[0][1];return entries.filter(([,v])=>v>=top*relativeCutoff).slice(0,limit).map(([k])=>k)}
function ecoToOpening(eco:string):[string,string,string]{const e=eco.toUpperCase();const n=Number(e.slice(1));if(!/^[A-E]\d\d$/.test(e))return['','',''];const l=e[0];if(l==='B'){if(n>=20&&n<=99){let v=n>=90?'Najdorf':n>=80?'Scheveningen':n>=70?'Dragon':n>=50?'Classical':n>=40?'Kan':n>=30?'Open Sicilian':'Anti-Sicilian';return['Sicilian Defense',v,'']}if(n>=10&&n<=19)return['Caro-Kann Defense','',''];if(n>=2&&n<=5)return['Alekhine Defense','',''];if(n>=6&&n<=9)return['Modern Defense / Pirc Defense','',''];if(n===1)return['Scandinavian Defense','',''];}
if(l==='C'){if(n>=0&&n<=19)return['French Defense','',''];if(n>=20&&n<=59)return['Open Games','',''];if(n>=60&&n<=99){let v=n>=90?'Closed Ruy Lopez':n>=80?'Open Ruy Lopez':n>=70?'Exchange / Modern Steinitz':n>=65?'Berlin Defense':'Ruy Lopez';return['Ruy Lopez',v,''];}}
if(l==='D'){if(n<=5)return["Queen's Pawn Game",'', ''];if(n>=6&&n<=69){if(n>=10&&n<=19)return["Queen's Gambit Declined",'Slav Defense',''];if(n>=20&&n<=29)return["Queen's Gambit Accepted",'', ''];if(n>=30&&n<=69)return["Queen's Gambit Declined",'', ''];return["Queen's Gambit",'', ''];}if(n>=70&&n<=79)return['Neo-Grunfeld Defense','', ''];if(n>=80&&n<=99)return['Grunfeld Defense',n>=85?'Exchange Variation':'', ''];}
if(l==='E'){if(n<=9)return['Catalan Opening / Queen’s Indian / Bogo-Indian','', ''];if(n>=20&&n<=59)return['Nimzo-Indian Defense','', ''];if(n>=60&&n<=99)return["King’s Indian Defense",'', ''];}
return['','',''];}
function opening(headers:PgnHeaders):[string,string,string]{const sub=headers.SubVariation||headers.Subvariation||'';if(headers.Opening||headers.Variation||sub)return[headers.Opening||'',headers.Variation||'',sub];return ecoToOpening(headers.ECO||'')}
function fenMaterial(fen?:string){const board=(fen||'').split(' ')[0]||'';const m={q:0,r:0,b:0,n:0,p:0,total:0};for(const ch of board.toLowerCase())if('qrbnpk'.includes(ch)){if(ch!=='k'){(m as any)[ch]++;m.total++}}return m}
export function inferPhase(pathText:string,text:string,fen?:string):string{const mat=fen?fenMaterial(fen):undefined;if(mat){if(mat.total<=8)return'Endgame';if(mat.q===0&&mat.total<=12)return'Endgame';if(mat.total<=18)return'Middlegame'}const p=normalizeText(pathText),t=normalizeText(text);if(/endings|endgame|rook ending|studies/.test(p))return'Endgame';if(/opening|openings|repertoire/.test(p))return'Opening';if(t.includes('in the opening')||t.includes('opening stages')||t.includes('develop your pieces'))return'Opening';if(/endgame|ending|rook ending|pawn ending/.test(t))return'Endgame';return'Middlegame'}
export function inferDomain(pathText:string,text:string,phase:string):string{const scores=scoreRules(pathText+' '+text,DOMAIN_RULES);if(phase==='Endgame')scores.set('Endgame',(scores.get('Endgame')||0)+3);if(phase==='Opening')scores.set('Opening',(scores.get('Opening')||0)+3);if(!scores.size)return phase==='Middlegame'?'Strategy':phase;return topLabels(scores,1,1,0)[0]}
function inferMaterial(text:string,fen:string|undefined,phase:string):string[]{const scores=scoreRules(text,MATERIAL_RULES);const mat=fen?fenMaterial(fen):undefined;if(mat){if(mat.r>=2&&mat.q===0&&mat.total<=10)scores.set('Rook endgame',(scores.get('Rook endgame')||0)+5);if(mat.q>=1&&mat.total<=8)scores.set('Queen endgame',(scores.get('Queen endgame')||0)+5);if(mat.r===0&&mat.b===0&&mat.n===0&&mat.p>0)scores.set('Pawn endgame',(scores.get('Pawn endgame')||0)+5)}const tags=topLabels(scores,4,1,0.35);if(phase==='Endgame'&&!tags.length)tags.push('General endgame');return tags}
function inferThemes(pathText:string,text:string,phase:string,domain:string){const all=pathText+' '+text;const primary=scoreRules(all,PRIMARY_THEME_RULES),micro=scoreRules(all,MICRO_TAG_RULES),structures=scoreRules(all,STRUCTURE_RULES);if(domain==='Endgame'||phase==='Endgame')for(const l of ['King activity','Rook activity','Opposition','Passed pawn'])if(primary.has(l))primary.set(l,primary.get(l)!+2);if(domain==='Tactics')for(const l of ['Mating net','Sacrifice','Fork','Pin','Deflection'])if(primary.has(l))primary.set(l,primary.get(l)!+2);if(/combinations?/.test(normalizeText(pathText))){primary.set('Mating net',(primary.get('Mating net')||0)+4);primary.set('Sacrifice',(primary.get('Sacrifice')||0)+4)}return{primary_themes:topLabels(primary,4,2,0.35),micro_tags:topLabels(micro,6,2,0.3),structures:topLabels(structures,3,2,0.35)}}
function confidence(h:PgnHeaders,primary:string[],micro:string[]):number{let x=0.2;if(h.ECO)x+=0.2;if(h.Opening)x+=0.2;if(h.Annotator)x+=0.1;x+=Math.min(0.2,primary.length*0.05);x+=Math.min(0.1,micro.length*0.02);return Math.round(Math.min(0.95,x)*100)/100}
export function classifyPgnText(raw:string,source_file='pasted.pgn'):TaxonomyRow[]{return splitGames(raw).map((g,i)=>{const h=parseHeaders(g);const comments=extractComments(g).join(' ');const moves=stripHeadersAndComments(g);const text=[Object.values(h).join(' '),comments,moves].join(' ');const [fam,varn,sub]=opening(h);const phase=inferPhase(source_file,text,h.FEN);const domain=inferDomain(source_file,text,phase);const th=inferThemes(source_file,text,phase,domain);if(!th.primary_themes.length)th.primary_themes=[domain==='Endgame'?'King activity':domain==='Tactics'?'Mating net':'Typical plan'];return{source_file,game_index:i+1,event:h.Event||'',white:h.White||'',black:h.Black||'',result:h.Result||'',eco:h.ECO||'',annotator:h.Annotator||'',opening_family:fam,opening_variation:varn,opening_subvariation:sub,phase,domain,...th,material_tags:inferMaterial(source_file+' '+text,h.FEN,phase),confidence:confidence(h,th.primary_themes,th.micro_tags),headers:h,raw_pgn_preview:g.slice(0,1200)}})}
