import type {TaxonomyRule} from './types.js';
export const DOMAIN_RULES:TaxonomyRule[]=[
{label:'Tactics',keywords:['tactic','tactics','combination','combinations','attack','mate','mating','sacrifice','sac','fork','pin','skewer','deflection','decoy','discovered attack','zwischenzug'],weight:3},
{label:'Strategy',keywords:['strategy','strategic','plan','planning','maneuver','manoeuvre','prophylaxis','weak square','outpost','space advantage','initiative','piece activity'],weight:2},
{label:'Opening',keywords:['opening','openings','repertoire','novelty','theory','gambit','variation','line','develop','development'],weight:2},
{label:'Endgame',keywords:['endgame','ending','endings','rook ending','pawn ending','study','studies','lucena','philidor','opposition','triangulation'],weight:3},
{label:'Calculation',keywords:['calculate','calculation','candidate move','candidate moves','forced line','forcing move','visualization','variation tree'],weight:2},
{label:'Defense',keywords:['defense','defence','defensive','defend','counterplay','fortress','blockade','hold the draw'],weight:2},
];
export const PRIMARY_THEME_RULES:TaxonomyRule[]=[
{label:'Mating net',keywords:['mate','checkmate','mating net','king hunt','back rank mate','smothered mate'],weight:4},
{label:'Sacrifice',keywords:['sacrifice','sacrifices','sac','exchange sacrifice','piece sacrifice','bishop sacrifice','rook sacrifice'],weight:3},
{label:'Fork',keywords:['fork','forks','double attack','knight fork'],weight:4},
{label:'Pin',keywords:['pin','pinned','absolute pin','relative pin'],weight:3},
{label:'Deflection',keywords:['deflection','deflect','decoy','overloaded'],weight:3},
{label:'Discovered attack',keywords:['discovered attack','discovered check','double check'],weight:3},
{label:'Passed pawn',keywords:['passed pawn','passed pawns','passer','outside passer','connected passed pawns'],weight:3},
{label:'King activity',keywords:['king activity','active king','king centralization','centralize the king'],weight:3},
{label:'Rook activity',keywords:['rook activity','active rook','rook behind','seventh rank','7th rank'],weight:3},
{label:'Opposition',keywords:['opposition','distant opposition','trébuchet','trebuchet','triangulation'],weight:4},
{label:'Lucena',keywords:['lucena','bridge building','build a bridge'],weight:5},
{label:'Philidor',keywords:['philidor','third rank defense','third rank defence'],weight:5},
{label:'Typical plan',keywords:['typical plan','standard plan','minority attack','pawn break','breakthrough','improve pieces'],weight:2},
];
export const MICRO_TAG_RULES:TaxonomyRule[]=[
// Tactical motifs
{label:'Back rank',keywords:['back rank','back-rank'],weight:3},
{label:'Zwischenzug',keywords:['zwischenzug','in between move','intermezzo','intermediate move'],weight:3},
{label:'Clearance',keywords:['clearance','clear a square','clear the file','square clearance'],weight:2},
{label:'Overloading',keywords:['overload','overloaded','overloading','overworked'],weight:3},
{label:'X-ray attack',keywords:['x-ray','xray','x ray attack','skewer'],weight:3},
{label:'Interference',keywords:['interference','interfere','cut off','intercept'],weight:2},
{label:'Windmill',keywords:['windmill','perpetual check','see-saw'],weight:3},
{label:'Zugzwang',keywords:['zugzwang','must move','losing tempo','no good moves'],weight:4},
{label:'Stalemate trap',keywords:['stalemate','stalemate trap','draw by stalemate'],weight:3},
{label:'Underpromotion',keywords:['underpromotion','underpromote','promote to knight','promote to bishop','promote to rook'],weight:3},
{label:'Domination',keywords:['domination','dominating','trapped piece','knight domination','bishop domination'],weight:2},
{label:'Tempo',keywords:['tempo','gain tempo','lose tempo','losing a tempo','tempo move','with tempo'],weight:2},
{label:'Battery',keywords:['battery','double rook','rooks doubled','rook battery','queen and rook'],weight:2},
// Positional motifs
{label:'Outpost',keywords:['outpost','outposts','strong square','knight outpost'],weight:2},
{label:'Weak squares',keywords:['weak square','weak squares','holes','color weakness','color complex'],weight:2},
{label:'Open file',keywords:['open file','half open file','file control','open the file','semi-open'],weight:2},
{label:'Pawn break',keywords:['pawn break','break with','breakthrough','pawn advance'],weight:2},
{label:'King safety',keywords:['king safety','unsafe king','exposed king','king weakness','attack the king'],weight:2},
{label:'Development',keywords:['development','develop your pieces','lead in development','developing move'],weight:2},
{label:'Prophylaxis',keywords:['prophylaxis','prophylactic','prevent','anticipate','stop counterplay'],weight:2},
{label:'Initiative',keywords:['initiative','seize the initiative','maintain the initiative','active play'],weight:2},
{label:'Space advantage',keywords:['space advantage','space','control the center','central control'],weight:2},
{label:'Piece coordination',keywords:['piece coordination','harmony','coordinate','active pieces'],weight:2},
{label:'Compensation',keywords:['compensation','compensate','positional compensation','material deficit'],weight:2},
{label:'Exchange advantage',keywords:['exchange advantage','exchange the pieces','favorable exchange','trade'],weight:1},
{label:'Bishop pair',keywords:['bishop pair','two bishops','pair of bishops'],weight:3},
{label:'Bad bishop',keywords:['bad bishop','passive bishop','blocked bishop','wrong bishop'],weight:2},
{label:'Good knight vs bad bishop',keywords:['knight vs bishop','good knight','knight better than bishop'],weight:2},
{label:'Minority attack',keywords:['minority attack','queenside minority','wing attack'],weight:3},
{label:'Pawn storm',keywords:['pawn storm','pawn advance','pawn push','queenside storm','kingside storm'],weight:2},
{label:'Queenside attack',keywords:['queenside attack','queenside play','queenside expansion'],weight:2},
{label:'Kingside attack',keywords:['kingside attack','kingside play','attack on the king','kingside expansion'],weight:2},
{label:'Rook lift',keywords:['rook lift','lift the rook','rook to third','rook to h3','rook transfer'],weight:2},
{label:'Knight maneuver',keywords:['knight maneuver','knight tour','reposition the knight','knight retreat','knight reroute'],weight:2},
{label:'Weak color complex',keywords:['color complex','weak color','dark squares','light squares','color weakness'],weight:2},
{label:'Fortress',keywords:['fortress','draw fortress','blockade fortress','passive defense'],weight:3},
{label:'Counterplay',keywords:['counterplay','counter-attack','counterattack','active defense','create counterplay'],weight:2},
// Endgame micro-tags
{label:'King and pawn',keywords:['king and pawn','k+p endgame','pawn endgame','key squares','key square','rule of the square'],weight:2},
{label:'Outside passed pawn',keywords:['outside passed pawn','outside passer','distraction','decoy pawn'],weight:3},
{label:'Pawn majority',keywords:['pawn majority','queenside majority','kingside majority','pawn advantage'],weight:2},
{label:'Rook behind passer',keywords:['rook behind passed pawn','rook behind passer','active rook'],weight:2},
{label:'Triangulation',keywords:['triangulation','lose a tempo','triangulate'],weight:3},
{label:'Time trouble',keywords:['time trouble','zeitnot','time pressure'],weight:1},
{label:'Conversion',keywords:['conversion','convert','technical win','technique'],weight:2},
{label:'Drawing technique',keywords:['draw','drawing technique','hold the draw','perpetual','fifty move'],weight:2},
{label:'Pawn structure',keywords:['pawn structure','pawn formation','pawn chain','pawn skeleton'],weight:1},
{label:'Open center',keywords:['open center','open game','central tension','central pawn break'],weight:2},
{label:'Closed position',keywords:['closed position','closed game','locked center','blocked position'],weight:2},
{label:'Dynamic play',keywords:['dynamic','imbalance','compensation','unbalanced','complex position'],weight:1},
{label:'Simplification',keywords:['simplification','simplify','trade off','exchange to endgame'],weight:2},
{label:'Blockade',keywords:['blockade','blockader','blockading piece','blockaded pawn'],weight:2},
];
export const STRUCTURE_RULES:TaxonomyRule[]=[
{label:'Isolated queen pawn',keywords:['isolated queen pawn','isolated pawn','iqp'],weight:3},
{label:'Hanging pawns',keywords:['hanging pawns'],weight:3},
{label:'Carlsbad structure',keywords:['carlsbad','minority attack'],weight:3},
{label:'Passed pawn structure',keywords:['passed pawn','passed pawns','passer'],weight:2},
{label:'Doubled pawns',keywords:['doubled pawns','doubled pawn'],weight:2},
{label:'Backward pawn',keywords:['backward pawn','backward pawns'],weight:2},
{label:'Pawn majority',keywords:['pawn majority','queenside majority','kingside majority'],weight:2},
{label:'Locked center',keywords:['locked center','closed center','blocked center'],weight:2},
{label:'Pawn chain',keywords:['pawn chain','pawn formation','pawn skeleton'],weight:2},
{label:'Isolated pawn',keywords:['isolated pawn','isolani'],weight:2},
{label:'Connected pawns',keywords:['connected passed pawns','connected pawns'],weight:2},
];
export const MATERIAL_RULES:TaxonomyRule[]=[
{label:'Rook endgame',keywords:['rook endgame','rook ending','rook endings','lucena','philidor'],weight:4},
{label:'Queen endgame',keywords:['queen endgame','queen ending'],weight:3},
{label:'Pawn endgame',keywords:['pawn endgame','pawn ending','king and pawn'],weight:4},
{label:'Minor piece endgame',keywords:['minor piece endgame','bishop ending','knight ending','opposite colored bishops','opposite-coloured bishops'],weight:3},
{label:'Exchange sacrifice',keywords:['exchange sacrifice','exchange sac'],weight:3},
{label:'Opposite-colored bishops',keywords:['opposite colored bishops','opposite-coloured bishops'],weight:3},
{label:'Queen vs rook',keywords:['queen vs rook','queen against rook'],weight:3},
{label:'Rook vs minor piece',keywords:['rook vs knight','rook vs bishop','rook against minor'],weight:2},
{label:'General endgame',keywords:['endgame','ending','study','studies'],weight:1},
];
