import type {TaxonomyRule} from './types.js';
export const DOMAIN_RULES:TaxonomyRule[]=[
{label:'Tactics',keywords:['tactic','tactics','combination','combinations','attack','mate','mating','sacrifice','sac','fork','pin','skewer','deflection','decoy','discovered attack','zwischenzug'],weight:3},
{label:'Strategy',keywords:['strategy','strategic','plan','planning','maneuver','manoeuvre','prophylaxis','weak square','outpost','space advantage','initiative','piece activity'],weight:2},
{label:'Opening',keywords:['opening','openings','repertoire','novelty','theory','gambit','variation','line','develop','development'],weight:2},
{label:'Endgame',keywords:['endgame','ending','endings','rook ending','pawn ending','study','studies','lucena','philidor','opposition','triangulation'],weight:3},
{label:'Calculation',keywords:['calculate','calculation','candidate move','candidate moves','forced line','forcing move','visualization','variation tree'],weight:2},
{label:'Defense',keywords:['defense','defence','defensive','defend','counterplay','fortress','blockade','hold the draw'],weight:2},
];
export const PRIMARY_THEME_RULES:TaxonomyRule[]=[
{label:'Mating net',keywords:['mate','checkmate','mating net','king hunt','back rank mate','smothered mate','design for checkmate','mating attack','mating habits'],weight:4},
{label:'Sacrifice',keywords:['sacrifice','sacrifices','sac','exchange sacrifice','exchange sac','piece sacrifice','bishop sacrifice','rook sacrifice','shunning sacrifice','unpinning sacrifice'],weight:3},
{label:'Fork',keywords:['fork','forks','double attack','knight fork'],weight:4},
{label:'Pin',keywords:['pin','pinned','absolute pin','relative pin','unpinning'],weight:3},
{label:'Deflection',keywords:['deflection','deflect','decoy','decoying','diversion','overloaded'],weight:3},
{label:'Discovered attack',keywords:['discovered attack','discovered check','double check'],weight:3},
{label:'Passed pawn',keywords:['passed pawn','passed pawns','passer','outside passer','connected passed pawns','powerful passed pawns','passed pawn lust','pawn promotion','queening','promoting a pawn','promote a pawn'],weight:3},
{label:'King activity',keywords:['king activity','active king','king centralization','centralize the king','king is a strong piece','king march','king walk','the modern king'],weight:3},
{label:'Rook activity',keywords:['rook activity','active rook','rook behind','seventh rank','7th rank','rook on the seventh','rook on seventh','rook on 7th','mysterious rook','swinging rook'],weight:3},
{label:'Opposition',keywords:['opposition','distant opposition','trébuchet','trebuchet','triangulation'],weight:4},
{label:'Lucena',keywords:['lucena','bridge building','build a bridge'],weight:5},
{label:'Philidor',keywords:['philidor','third rank defense','third rank defence'],weight:5},
{label:'Typical plan',keywords:['typical plan','standard plan','minority attack','pawn break','breakthrough','improve pieces'],weight:2},
];
export const MICRO_TAG_RULES:TaxonomyRule[]=[
// ── Core tactical motifs (appear as chapter titles) ──────────────────────────
{label:'Pawn promotion',keywords:['pawn promotion','queening','promoting a pawn','promote a pawn','queen a pawn','queening combinations','queening the pawn','promote the pawn','promotion combinations'],weight:5},
{label:'Back rank',keywords:['back rank','back-rank','first rank','vulnerable first rank'],weight:4},
{label:'Removing the guard',keywords:['removing the guard','remove the guard','eliminate the defender','removing a defender','overloading the guard'],weight:4},
{label:'Zwischenzug',keywords:['zwischenzug','in-between move','in between move','intermezzo','intermediate move'],weight:4},
{label:'Clearance',keywords:['clearance','square clearance','clear a square','clear the file','line clearance','clearance sacrifice'],weight:3},
{label:'Overloading',keywords:['overload','overloaded','overloading','overworked','the overworked piece'],weight:3},
{label:'Trapped piece',keywords:['trapped piece','trapped the piece','piece is trapped','piece trap','trap a piece'],weight:4},
{label:'X-ray attack',keywords:['x-ray','xray','x ray attack'],weight:3},
{label:'Fork',keywords:['fork','forks','double attack','knight fork','forking'],weight:4},
{label:'Pin',keywords:['pin','pinned','pinning','absolute pin','relative pin'],weight:4},
{label:'Deflection',keywords:['deflection','deflect','decoy','decoying','diversion'],weight:4},
{label:'Discovered attack',keywords:['discovered attack','discovered check','double check','double-check'],weight:4},
{label:'Skewer',keywords:['skewer','skewering','skewered'],weight:4},
{label:'Interference',keywords:['interference','interfere','intercept','cut off'],weight:3},
{label:'Windmill',keywords:['windmill','see-saw','see saw check'],weight:4},
{label:'Perpetual check',keywords:['perpetual check','perpetual','draw by perpetual'],weight:4},
{label:'Zugzwang',keywords:['zugzwang','must move','no good moves','five steps of zugzwang'],weight:5},
{label:'Stalemate',keywords:['stalemate','stalemate combinations','stalemate trap','draw by stalemate'],weight:4},
{label:'Underpromotion',keywords:['underpromotion','underpromote','promote to knight','promote to bishop','promote to rook'],weight:4},
{label:'Combination',keywords:['combination','combinations','combinations involving','combining tactical'],weight:2},
{label:'Ambush',keywords:['ambush','surprise move','the sting in the tail'],weight:3},
{label:'Decoy',keywords:['decoy','decoying','lure','attraction'],weight:3},
{label:'Double check',keywords:['double check','double-check'],weight:4},
{label:'Domination',keywords:['domination','dominating','trapped piece','knight domination','bishop domination'],weight:2},
{label:'Tempo',keywords:['tempo','gain tempo','lose tempo','sensing the tempo','losing a tempo','with tempo'],weight:3},
{label:'Battery',keywords:['battery','double rook','rooks doubled','rook battery','alekhine\'s gun'],weight:3},
{label:'Mating attack',keywords:['mating attack','king hunt','design for checkmate','attack on the king','direct attack','brilliant blunder'],weight:3},
// ── Positional & strategic concepts ──────────────────────────────────────────
{label:'Outpost',keywords:['outpost','outposts','magnificent outpost','strong square','knight outpost'],weight:3},
{label:'Weak squares',keywords:['weak square','weak squares','holes','color weakness','color complex','making use of a weak square','dark squares','light squares'],weight:2},
{label:'Open file',keywords:['open file','half open file','semi-open file','file control','open the file','penetration down an open file','domination of open files','open lines'],weight:2},
{label:'Pawn break',keywords:['pawn break','break with','breakthrough','the fearless break','pawn advance','en-passant break','en passant break'],weight:2},
{label:'King safety',keywords:['king safety','unsafe king','exposed king','king weakness','king in the center','king in the centre','king position','king not castled'],weight:2},
{label:'Development',keywords:['development','develop your pieces','lead in development','a lead in development','developing move','mobilization'],weight:2},
{label:'Prophylaxis',keywords:['prophylaxis','prophylactic','provocation and prophylaxis','prevent','preventing counterplay','anticipate','stop counterplay'],weight:2},
{label:'Initiative',keywords:['initiative','seize the initiative','maintain the initiative','active play','capture of the initiative'],weight:2},
{label:'Space advantage',keywords:['space advantage','space','control the center','central control','the dark side of space'],weight:2},
{label:'Piece coordination',keywords:['piece coordination','harmony','coordinate','active pieces','coordination of pieces','coordination of the pieces'],weight:2},
{label:'Compensation',keywords:['compensation','compensate','positional compensation','material deficit','imbalance'],weight:2},
{label:'Bishop pair',keywords:['bishop pair','two bishops','pair of bishops','the two bishops','two bishops victorious','bishops of the same color'],weight:3},
{label:'Bad bishop',keywords:['bad bishop','passive bishop','blocked bishop','wrong bishop','good or bad bishop','good bishop and bad bishop','buried bishop'],weight:3},
{label:'Good knight vs bad bishop',keywords:['knight vs bishop','bishop vs knight','good knight','knight better than bishop','dogs vs cats','dogs vs. cats'],weight:3},
{label:'Minority attack',keywords:['minority attack','queenside minority','wing attack','lesson in minority attack'],weight:3},
{label:'Opposite-side castling',keywords:['opposite sides','opposite wing','storming a kingside','castled on opposite sides','opposite castling'],weight:3},
{label:'Pawn storm',keywords:['pawn storm','pawn advance','pawn push','queenside storm','kingside storm','pawn-dash'],weight:2},
{label:'Queenside attack',keywords:['queenside attack','queenside play','queenside expansion'],weight:2},
{label:'Kingside attack',keywords:['kingside attack','kingside play','attack on the king','kingside expansion','king-side attack','attacking after kingside castling','storming a kingside','firing at the fianchetto'],weight:2},
{label:'Rook lift',keywords:['rook lift','lift the rook','rook to third','swinging rook','rocking rook'],weight:2},
{label:'Knight maneuver',keywords:['knight maneuver','knight tour','reposition the knight','knight retreat','knight reroute','don\'t move your knight'],weight:2},
{label:'Restraint',keywords:['restraint','restrict','blockade before','big squeeze','systematic strangulation','strangulation','squeeze'],weight:3},
{label:'Weak color complex',keywords:['color complex','weak color','dark squares','light squares','color weakness'],weight:2},
{label:'Fortress',keywords:['fortress','draw fortress','blockade fortress','passive defense','fortress question'],weight:3},
{label:'Counterplay',keywords:['counterplay','counter-attack','counterattack','active defense','create counterplay','preventing counterplay'],weight:2},
{label:'Seventh rank',keywords:['seventh rank','7th rank','rook on the seventh','rook on 7th','the vulnerable first rank','first rank'],weight:3},
{label:'Pawn wedge',keywords:['pawn wedge','phalanx','pawn phalanx','pawn chain','5 vs 4'],weight:2},
{label:'Penetration',keywords:['penetration','infiltration','invade','invasion','penetration down'],weight:2},
{label:'Piece activity',keywords:['piece activity','improving pieces','activate','active pieces','improve the pieces'],weight:1},
{label:'Exchange sacrifice',keywords:['exchange sacrifice','exchange sac','exchange sacs','brutal exchange sac'],weight:3},
// ── Endgame micro-tags ────────────────────────────────────────────────────────
{label:'King and pawn',keywords:['king and pawn','k+p endgame','pawn endgame','key squares','key square','rule of the square'],weight:2},
{label:'Outside passed pawn',keywords:['outside passed pawn','outside passer','distraction','decoy pawn','pawn expendable'],weight:3},
{label:'Pawn majority',keywords:['pawn majority','queenside majority','kingside majority','pawn advantage','understanding pawn majorities'],weight:2},
{label:'Rook behind passer',keywords:['rook behind passed pawn','rook behind passer','active rook'],weight:2},
{label:'Triangulation',keywords:['triangulation','lose a tempo','triangulate'],weight:3},
{label:'Drawing technique',keywords:['draw','drawing technique','hold the draw','fifty move','defensive resources'],weight:2},
{label:'Simplification',keywords:['simplification','simplify','trade off','exchange to endgame','17 the art of exchanging pieces'],weight:2},
{label:'Blockade',keywords:['blockade','blockader','blockading piece','blockaded pawn','block before you punch'],weight:3},
{label:'Opposite-colored bishops',keywords:['opposite colored bishops','opposite-coloured bishops','opposite-colored bishops','bishops of same color'],weight:3},
{label:'Backward pawn',keywords:['backward pawn','backward pawns'],weight:2},
{label:'Isolated pawn',keywords:['isolated pawn','isolated queen pawn','isolani','double isolated'],weight:2},
{label:'Pawn structure',keywords:['pawn structure','pawn formation','pawn skeleton','pawn weaknesses','weak pawns','pawns passed and present'],weight:1},
{label:'Dynamic play',keywords:['dynamic','imbalance','unbalanced','complex position','dynamism'],weight:1},
{label:'Conversion',keywords:['conversion','convert','technical win','technique'],weight:2},
{label:'Time trouble',keywords:['time trouble','zeitnot','time pressure'],weight:1},
{label:'Open center',keywords:['open center','open game','central tension','central pawn break','indestructible center'],weight:2},
{label:'Closed position',keywords:['closed position','closed game','locked center','blocked position'],weight:2},
];
export const STRUCTURE_RULES:TaxonomyRule[]=[
{label:'Isolated queen pawn',keywords:['isolated queen pawn','isolated pawn','iqp'],weight:3},
{label:'Hanging pawns',keywords:['hanging pawns'],weight:3},
{label:'Carlsbad structure',keywords:['carlsbad','minority attack'],weight:3},
{label:'Passed pawn structure',keywords:['passed pawn','passed pawns','passer'],weight:2},
{label:'Doubled pawns',keywords:['doubled pawns','doubled pawn','double isolated d-pawns'],weight:2},
{label:'Backward pawn',keywords:['backward pawn','backward pawns'],weight:2},
{label:'Pawn majority',keywords:['pawn majority','queenside majority','kingside majority'],weight:2},
{label:'Locked center',keywords:['locked center','closed center','blocked center'],weight:2},
{label:'Pawn chain',keywords:['pawn chain','pawn formation','pawn skeleton'],weight:2},
{label:'Isolated pawn',keywords:['isolated pawn','isolani'],weight:2},
{label:'Connected pawns',keywords:['connected passed pawns','connected pawns'],weight:2},
];
export const MATERIAL_RULES:TaxonomyRule[]=[
{label:'Rook endgame',keywords:['rook endgame','rook ending','rook endings','rook and pawn ending','lucena','philidor'],weight:4},
{label:'Queen endgame',keywords:['queen endgame','queen ending','queen endgames'],weight:3},
{label:'Pawn endgame',keywords:['pawn endgame','pawn ending','king and pawn','pawn endings'],weight:4},
{label:'Knight endgame',keywords:['knight endgame','knight ending','knight endgames'],weight:4},
{label:'Bishop endgame',keywords:['bishop endgame','bishop ending'],weight:3},
{label:'Minor piece endgame',keywords:['minor piece endgame','bishop ending','knight ending','opposite colored bishops','opposite-coloured bishops'],weight:3},
{label:'Exchange sacrifice',keywords:['exchange sacrifice','exchange sac'],weight:3},
{label:'Opposite-colored bishops',keywords:['opposite colored bishops','opposite-coloured bishops'],weight:3},
{label:'Queen vs rook',keywords:['queen vs rook','queen against rook','queen or two rooks'],weight:3},
{label:'Rook vs minor piece',keywords:['rook vs knight','rook vs bishop','rook vs. knight','rook vs. bishop','rook against minor'],weight:3},
{label:'General endgame',keywords:['endgame','ending','study','studies'],weight:1},
];
